version: "3.7"

networks:
    laravel :
        driver: bridge

services:
    app:
        build:
            args:
                user: "antoine"
                uid: 1001
            context: ./bin/php
            dockerfile: Dockerfile
        image: laravel
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./www/:/var/www
        networks:
            - laravel
        links: 
            - database
    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./www/:/var/www
            - ./bin/nginx:/etc/nginx/conf.d
        networks:
            - laravel
    database:
        image: mariadb:latest
        container_name: laravel-db
        restart: unless-stopped
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: "laravel"
            MYSQL_ROOT_PASSWORD: "laravel"
            MYSQL_PASSWORD: "laravel"
            MYSQL_USER: "laravel"
        networks:
            - laravel
